import { ClerkProvider, currentUser } from "@clerk/nextjs";
import "@uploadthing/react/styles.css";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TopBar from "@/components/Bars/Topbar";
import Bottombar from "@/components/Bars/Bottombar";
import LeftSidebar from "@/components/Bars/LeftSidebar";
import RightSidebar from "@/components/Bars/RightSidebar";
import { dark } from "@clerk/themes";
import { UserDataType } from "@/lib/types";
import { fetchUserDetails } from "@/lib/actions/user.action";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SocialX",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await currentUser();
  if (!user) return null;

  const userInfo: UserDataType = await fetchUserDetails(user.id);

  if (!userInfo || !userInfo.onboarded) redirect("/onboarding");

  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body
          className={`${inter.className} bg-dark-1 text-white bg-black h-screen`}
        >
          <div className="flex flex-col w-full items-center h-full">
            <TopBar profileUrl = {userInfo.image}/>
            <div className="flex w-full h-full">
              <LeftSidebar />
              {children}
              {/* <RightSidebar /> */}
            </div>
            <Bottombar />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
